# Manager keymaps ----------------------------------------------
[[mgr.prepend_keymap]]
on = [ "<C-j>" ]
run = "arrow 1"
desc = "Move cursor down"

[[mgr.prepend_keymap]]
on = [ "<C-k>" ]
run = "arrow -1"
desc = "Move cursor up"

[[mgr.prepend_keymap]]
on = [ "<C-e>" ]
run = 'seek +5'
desc = "Seek down 5 lines"

[[mgr.prepend_keymap]]
on = [ "<C-y>" ]
run = 'seek -5'
desc = "Seek up 5 lines"

[[mgr.prepend_keymap]]
on = [ "<C-s>" ]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

# Input keymaps ----------------------------------------------
[[input.prepend_keymap]]
on   = [ "<Esc>" ]
run  = "close"
desc = "Cancel input"

[[input.prepend_keymap]]
on = [ "l" ]
run = "plugin --sync smart-enter"
desc = "Enter child directory, or open file"

# Preview keymaps ----------------------------------------------
[[plugin.prepend_previewers]]
url = "*"
run = 'piper -- echo "$1"'

[[plugin.prepend_previewers]]
url = "*.csv"
run = 'piper -- bat -p --color=always "$1"'

[[plugin.prepend_previewers]]
url = ["*.md", "*.qmd"]
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

